### ISSUE TITLE
[Epic] calculator

### ISSUE THREAD

**Issue by kgpoj** [kgpoj/calculator#1]
# Overview
Implement a calculator component with basic computing functions, so that users can perform calculations without leaving the page

# UI design
<img width="334" alt="image" src="https://user-images.githubusercontent.com/73574762/221460311-813d5c47-4839-482b-b51e-a87d14da2835.png">

# In scope
- [ ] [display input number, based on the clicked number button](https://github.com/kgpoj/calculator/issues/2)
- [ ] [support plus/minus/multiple/division](https://github.com/kgpoj/calculator/issues/4)
- [ ] after clicking reset button, the number should reset to 0
- [ ] after clicking the `+/-` button, the number should switch between positive and negative
- [ ] after clicking the percentage button, the number should be divided by 100
- [ ] display `ERROR` when the dividend is 0, or the calculate result exceed JavaScript Number range

# Out of scope
- handle value exceed JavaScript Number range

# Technical approach

## 1. State management

> ### Option 1: store the data as a state of the parent component

### pros
- easy to start
### cons
- could be difficult for nested components to get and set data
  

> ### Option 2: useContext

### pros
- avoid the complexity of manually passing props
- lightweight to use
### cons
- when the data structure of a context is changed, it could be difficult to update all components using it

> ### Option 3: redux

### pros
- avoid the complexity of manually passing props
- easy to maintain complex states
- the debugging tool of redux could improve development efficiency
### cons
- for this small application, redux's state management may be too complex

# Test strategy
- specific test strategies will be included in each card
